# Generated by Django 5.2.4 on 2025-09-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_facalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='bloodgroub',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='student',
            name='education',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
