# Generated by Django 5.2.4 on 2025-09-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_address_student_bloodgroub_student_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.CharField(default='', max_length=10),
        ),
    ]
