# Generated by Django 5.2.6 on 2025-09-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300)),
                ('mobile', models.BigIntegerField()),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
